services:
    app:
        image: ghcr.io/maybe-finance/maybe:latest
        volumes:
            - app-storage:/rails/storage
        ports:
            - 3000:3000
        restart: unless-stopped
        environment:
            SELF_HOSTED: 'true'
            RAILS_FORCE_SSL: 'false'
            RAILS_ASSUME_SSL: 'false'
            GOOD_JOB_EXECUTION_MODE: async
            SECRET_KEY_BASE: 'WhRwx8hHIL/R2eNqP57N8AIB481yx+YcebgHyfZ7y38='
            DB_HOST: postgres
            POSTGRES_DB: 'maybe_local'
            POSTGRES_USER: 'maybe'
            POSTGRES_PASSWORD: 'password'
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres:16
        restart: unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: 'maybe'
            POSTGRES_DB: 'maybe_local'
            POSTGRES_PASSWORD: 'password'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    app-storage:
    postgres-data:
